  MODULE('LEARNMIL006.CLW')
U_TOOs                 PROCEDURE                      !Form TheaterOfOps
B_Missions             PROCEDURE                      !Browse the MilMissions file
BrowseOrgMissionsByOrgMiss:KMission PROCEDURE         !Browse the OrgMissions file by OrgMiss:KMission
U_Missions             PROCEDURE                      !Form MilMissions
UpdateOrgMissions      PROCEDURE                      !Form OrgMissions
  END
