  MODULE('LEARNMIL005.CLW')
U_c2ieActionResources  PROCEDURE                      !Form c2ieActionResources
B_c2ieActionObjectives PROCEDURE                      !Browse the c2ieActionObjectives file
U_c2ieActionObjectives PROCEDURE                      !Form c2ieActionObjectives
B_myOrganization       PROCEDURE                      !Browse the myOrganization file
U_myOrganization       PROCEDURE                      !Form myOrganization
B_OrgTOO               PROCEDURE                      !Browse the OrgTOO file
U_OrgTOO               PROCEDURE                      !Form OrgTOO
B_OrgMissions          PROCEDURE                      !Browse the OrgMissions file
U_OrgMissions          PROCEDURE                      !Form OrgMissions
B_TOOs                 PROCEDURE                      !Browse the TheaterOfOps file
  END
