  MODULE('LEARNMIL006.CLW')
U_TOOs                 PROCEDURE                      !Form TheaterOfOps
B_Missions             PROCEDURE                      !Browse the MilMissions file
BrowseOrgMissionsByOrgMiss:KMission PROCEDURE         !Browse the OrgMissions file by OrgMiss:KMission
U_Missions             PROCEDURE                      !Form MilMissions
UpdateOrgMissions      PROCEDURE                      !Form OrgMissions
B_C2IPExplorer         PROCEDURE                      !Browse the C2IPExplorer file
U_C2IPExplorer         PROCEDURE                      !Form C2IPExplorer
B_myOrgORBAT           PROCEDURE                      !Browse the myOrgORBAT file
U_myOrgORBAT           PROCEDURE                      !Form myOrgORBAT
B_MissionTASKORG       PROCEDURE                      !Browse the MissionTASKORG file
  END
